name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build distribution packages
      run: python -m build
    
    - name: Check distribution packages
      run: twine check dist/*
    
    - name: List built artifacts
      run: ls -lh dist/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: distribution-packages
        path: dist/
        retention-days: 30
    
    - name: Test installation from wheel
      run: |
        pip install dist/*.whl
        python -c "import techcompressor; print(f'Version: {techcompressor.__version__}')"
        techcompressor --version
    
    - name: Test installation from sdist
      run: |
        pip uninstall -y techcompressor
        pip install dist/*.tar.gz
        python -c "import techcompressor; print(f'Version: {techcompressor.__version__}')"
        techcompressor --version

  verify:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: distribution-packages
        path: dist/
    
    - name: Install from wheel
      run: |
        pip install dist/*.whl
    
    - name: Run smoke tests
      run: |
        pip install pytest
        pytest tests/test_release_smoke.py -v
