name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Run flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 techcompressor/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Report other issues (max line length 120, max complexity 15) but don't fail
        flake8 techcompressor/ tests/ --count --max-line-length=120 --max-complexity=15 --statistics --exit-zero
    
    - name: Check code formatting with black (report only)
      run: |
        black --check --line-length=120 techcompressor/ tests/ || echo "Black formatting issues found (not failing build)"
      continue-on-error: true
    
    - name: Check import sorting with isort (report only)
      run: |
        isort --check-only --profile=black --line-length=120 techcompressor/ tests/ || echo "Import sorting issues found (not failing build)"
      continue-on-error: true
